<a href="https://colab.research.google.com/github/MohneetKaur/NLP-using-GoogleColab/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [9]:
pip install tensorflow==2.12.*

In [10]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [11]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [26]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr) # returns index where the word was 1

[[40, 242, 152, 117], [40, 242, 152, 468], [40, 223, 152, 335], [119, 316, 406, 174, 241], [119, 316, 406, 174, 69], [465, 40, 249, 152, 56], [221, 24, 219, 174]]


### Word Embedding Represntation

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np

In [29]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  40 242 152 117]
 [  0   0   0   0  40 242 152 468]
 [  0   0   0   0  40 223 152 335]
 [  0   0   0 119 316 406 174 241]
 [  0   0   0 119 316 406 174  69]
 [  0   0   0 465  40 249 152  56]
 [  0   0   0   0 221  24 219 174]]


In [30]:
## 10 feature dimesnions
dim=10


In [31]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [33]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  40, 242, 152, 117], dtype=int32)

In [34]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 171ms/step


array([[-3.92261855e-02, -2.82040369e-02,  4.97449897e-02,
        -3.21421847e-02,  7.90311024e-03,  4.60354201e-02,
        -6.23713806e-03,  2.89757513e-02, -2.33320594e-02,
        -4.97848280e-02],
       [-3.92261855e-02, -2.82040369e-02,  4.97449897e-02,
        -3.21421847e-02,  7.90311024e-03,  4.60354201e-02,
        -6.23713806e-03,  2.89757513e-02, -2.33320594e-02,
        -4.97848280e-02],
       [-3.92261855e-02, -2.82040369e-02,  4.97449897e-02,
        -3.21421847e-02,  7.90311024e-03,  4.60354201e-02,
        -6.23713806e-03,  2.89757513e-02, -2.33320594e-02,
        -4.97848280e-02],
       [-3.92261855e-02, -2.82040369e-02,  4.97449897e-02,
        -3.21421847e-02,  7.90311024e-03,  4.60354201e-02,
        -6.23713806e-03,  2.89757513e-02, -2.33320594e-02,
        -4.97848280e-02],
       [-4.27697413e-02, -2.60407850e-03,  4.57087196e-02,
        -4.20808308e-02,  3.71035002e-02, -1.86497457e-02,
        -1.17281564e-02, -6.67747110e-03, -3.71776223e-02,
        -4.

In [35]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 37ms/step
[[[-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
    7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
   -2.33320594e-02 -4.97848280e-02]
  [-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
    7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
   -2.33320594e-02 -4.97848280e-02]
  [-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
    7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
   -2.33320594e-02 -4.97848280e-02]
  [-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
    7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
   -2.33320594e-02 -4.97848280e-02]
  [-4.27697413e-02 -2.60407850e-03  4.57087196e-02 -4.20808308e-02
    3.71035002e-02 -1.86497457e-02 -1.17281564e-02 -6.67747110e-03
   -3.71776223e-02 -4.47044857e-02]
  [-3.31827626e-02  2.44951248e-03  1.16032362e-02 -4.00090702e-02
   -3.22266594e-02  3.95322703e

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [36]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 18ms/step
[[-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
   7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
  -2.33320594e-02 -4.97848280e-02]
 [-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
   7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
  -2.33320594e-02 -4.97848280e-02]
 [-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
   7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
  -2.33320594e-02 -4.97848280e-02]
 [-3.92261855e-02 -2.82040369e-02  4.97449897e-02 -3.21421847e-02
   7.90311024e-03  4.60354201e-02 -6.23713806e-03  2.89757513e-02
  -2.33320594e-02 -4.97848280e-02]
 [-4.27697413e-02 -2.60407850e-03  4.57087196e-02 -4.20808308e-02
   3.71035002e-02 -1.86497457e-02 -1.17281564e-02 -6.67747110e-03
  -3.71776223e-02 -4.47044857e-02]
 [-3.31827626e-02  2.44951248e-03  1.16032362e-02 -4.00090702e-02
  -3.22266594e-02  3.95322703e-02 -1.25843175e-